# Basic Site Settings
locale: "fr-FR"
title: "Ahcene Benaissa - Ingénieur en Electronique Embarquée"
title_separator: "-"
name: "Ahcene Benaissa"
description: "Ingénieur en Electronique Embarquée | Machine Learning | Conception FPGA"
url: "https://votre-domaine.github.io" # Remplacez par votre URL
baseurl: ""

# Author Profile
author:
  avatar: "profile.png"
  name: "Ahcene Benaissa"
  bio: >
    Ingénieur en systèmes embarqués passionné par l'IA, les PCB et la co-conception matériel/logiciel.
    Actuellement en recherche de CDI pour des projets innovants en électronique embarquée.
  location: "Nancy 54000, France"
  employer: "Faculté des sciences et technologies Nancy"
  email: "contact@example.com"
  phone: "+33 7 52 19 09 66"
  linkedin: "linkedin.com/in/ahcene-benaissa"
  github: "votreusername" # Remplacer par votre GitHub

  # Compétences techniques
  skills:
    - "Systèmes embarqués (C/C++, Python)"
    - "Machine Learning & TensorFlow"
    - "Conception PCB (Altium, KiCad)"
    - "Protocoles de communication (I2C, SPI, UART)"
    - "VHDL/Verilog pour FPGA"

  # Langues
  languages:
    - "Français: Bilingue"
    - "Anglais: B2"
    - "Arabe: Langue maternelle"

  # Centres d'intérêt
  interests:
    - "Développement de systèmes IoT"
    - "Robotique autonome"
    - "Optimisation énergétique par IA"

# Section Formation
education:
  - degree: "Master EEA - Electronique Embarquée"
    institution: "Faculté des sciences et technologies Nancy"
    years: "2021-2024"

  - degree: "Licence 3 EEA - Systèmes Embarqués"
    institution: "Faculté des sciences et technologies Nancy" 
    years: "2020-2021"

# Section Expérience Professionnelle
experience:
  - position: "Stagiaire en Recherche"
    company: "Institut Jean Lamour"
    location: "Nancy"
    period: "2024 (6 mois)"
    details: "Développement d'un système de détection d'arcs électriques par IA"

  - position: "Intérimaire Technicien"
    company: "TECHNORAM"
    location: "Grand Est"
    period: "2023 (6 mois)"
    details: "Maintenance de systèmes électroniques industriels"

# Projets
projects:
  - title: "Système de localisation temps réel"
    description: "Développement matériel/logiciel avec filtrage Kalman"
    technologies: "C++, Python, STM32"
    
  - title: "Éclairage adaptatif intelligent"
    description: "Contrôle PWM avec capteurs ambiants"
    technologies: "Arduino, Capteurs IoT"

# Paramètres Techniques
excerpt_separator: "<!--more-->"
collections:
  publications:
    output: true
    permalink: /publications/:title/
    
  projects:
    output: true
    permalink: /projects/:path/

# Intégrations
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Paramètres avancés
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      author_profile: false
